// packages/shiki-magic-move/src/react/ShikiMagicMove.tsx
import type { HighlighterCore } from 'shiki/core'
import type { KeyedTokensInfo, MagicMoveDifferOptions, MagicMoveRenderOptions } from '../types'
import * as React from 'react'
import { codeToKeyedTokens, createMagicMoveMachine } from '../core'
import { ShikiMagicMoveRenderer } from './ShikiMagicMoveRenderer'

export interface ShikiMagicMoveProps {
  highlighter: HighlighterCore
  lang: string
  theme: string
  code: string
  options?: MagicMoveRenderOptions & MagicMoveDifferOptions
  onStart?: () => void
  onEnd?: () => void
  className?: string
  tabindex?: number
}

export function ShikiMagicMove(props: ShikiMagicMoveProps) {
  const codeToTokens = React.useRef<(code: string, lineNumbers?: boolean) => KeyedTokensInfo>()
  codeToTokens.current = (code, lineNumbers) =>
    codeToKeyedTokens(
      props.highlighter,
      code,
      {
        lang: props.lang,
        theme: props.theme,
      },
      lineNumbers,
    )

  const machine = React.useRef<ReturnType<typeof createMagicMoveMachine>>()
  machine.current =
    machine.current ||
    createMagicMoveMachine((code, lineNumbers) => codeToTokens.current!(code, lineNumbers))

  const lineNumbers = props.options?.lineNumbers ?? false

  const result = React.useMemo(() => {
    if (
      props.code === machine.current!.current.code &&
      props.theme === machine.current!.current.themeName &&
      props.lang === machine.current!.current.lang &&
      lineNumbers === machine.current!.current.lineNumbers
    ) {
      return machine.current!
    }

    return machine.current!.commit(props.code, props.options)
  }, [props.code, props.options, props.theme, props.lang, lineNumbers])

  return (
    <ShikiMagicMoveRenderer
      tokens={result.current}
      options={props.options}
      previous={result.previous}
      onStart={props.onStart}
      onEnd={props.onEnd}
      className={props.className}
    />
  )
}

// packages/shiki-magic-move/src/solid/ShikiMagicMove.tsx
/** @jsxImportSource solid-js */

import type { HighlighterCore } from 'shiki/core'
import { createMemo } from 'solid-js'
import { codeToKeyedTokens, createMagicMoveMachine } from '../core'
import type { MagicMoveDifferOptions, MagicMoveRenderOptions } from '../types'
import { ShikiMagicMoveRenderer } from './ShikiMagicMoveRenderer'

export interface ShikiMagicMoveProps {
  highlighter: HighlighterCore
  lang: string
  theme: string
  code: string
  options?: MagicMoveRenderOptions & MagicMoveDifferOptions
  onStart?: () => void
  onEnd?: () => void
  class?: string
  tabindex?: number
}

export function ShikiMagicMove(props: ShikiMagicMoveProps) {
  const codeToTokens = (code: string, lineNumbers?: boolean) =>
    codeToKeyedTokens(
      props.highlighter,
      code,
      {
        lang: props.lang,
        theme: props.theme,
      },
      lineNumbers,
    )

  const machine = createMagicMoveMachine((code, lineNumbers) => codeToTokens(code, lineNumbers))

  const result = createMemo(() => {
    const lineNumbers = props.options?.lineNumbers ?? false
    if (
      props.code === machine.current.code &&
      props.theme === machine.current.themeName &&
      props.lang === machine.current.lang &&
      lineNumbers === machine.current.lineNumbers
    ) {
      return machine
    }

    return machine.commit(props.code, props.options)
  })

  return (
    <ShikiMagicMoveRenderer
      tokens={result()?.current}
      options={props.options}
      previous={result()?.previous}
      onStart={props.onStart}
      onEnd={props.onEnd}
      class={props.class}
    />
  )
}
